apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: console
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'console-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/its-software-services-devops/k3s-argocd-demo-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/console'
      destination:
        name: in-cluster
        namespace: console
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
