apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'external-secrets-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/its-software-services-devops/k3s-argocd-demo-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/external-secrets'
      destination:
        name: in-cluster
        namespace: external-secrets
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
