apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: ssh-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: SSH_USER
    remoteRef:
      key: initial-secret
      property: SSH_USER

  - secretKey: SSH_PASSWORD
    remoteRef:
      key: initial-secret
      property: SSH_PASSWORD