apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: promtail-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: promtail-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: DEVICE_ID
    remoteRef:
      key: initial-secret
      property: DEVICE_ID

  - secretKey: REMOTE_LOKI_USER
    remoteRef:
      key: initial-secret
      property: REMOTE_LOKI_USER

  - secretKey: REMOTE_LOKI_PASSWORD
    remoteRef:
      key: initial-secret
      property: REMOTE_LOKI_PASSWORD

  - secretKey: REMOTE_LOKI_HOST
    remoteRef:
      key: initial-secret
      property: REMOTE_LOKI_HOST
