apiVersion: v2
name: helm-loki-promtail
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for promtail

dependencies:
  - name: promtail
    version: "6.10.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled
