promtail:
  enabled: true
  fullnameOverride: promtail-ext
  extraArgs:
    - "-config.expand-env=true"
  config:
    clients:
      - url: https://475784:${GRAFANA_API_KEY}@logs-prod-011.grafana.net/api/prom/push
    snippets:
      extraScrapeConfigs: |
        - job_name: system
          static_configs:
            - labels:
                device: ${DEVICE_ID}
              targets:
                - localhost
  extraEnv:
    - name: DEVICE_ID
      valueFrom:
        secretKeyRef:
          name: promtail-credentials
          key: DEVICE_ID
    - name: GRAFANA_API_KEY
      valueFrom:
        secretKeyRef:
          name: promtail-credentials
          key: GRAFANA_API_KEY
