promtail:
  enabled: true
  fullnameOverride: promtail-ext
  extraArgs:
    - "-config.expand-env=true"
  config:
    clients:
      - url: https://${REMOTE_LOKI_USER}:${REMOTE_LOKI_PASSWORD}@${REMOTE_LOKI_HOST}/api/prom/push
    snippets:
      pipelineStages:
        - cri: {}
        - static_labels:
            device_id: ${DEVICE_ID}
            category: k3s
  extraEnv:
    - name: DEVICE_ID
      valueFrom:
        secretKeyRef:
          name: promtail-credentials
          key: DEVICE_ID
    - name: REMOTE_LOKI_USER
      valueFrom:
        secretKeyRef:
          name: promtail-credentials
          key: REMOTE_LOKI_USER
    - name: REMOTE_LOKI_PASSWORD
      valueFrom:
        secretKeyRef:
          name: promtail-credentials
          key: REMOTE_LOKI_PASSWORD
    - name: REMOTE_LOKI_HOST
      valueFrom:
        secretKeyRef:
          name: promtail-credentials
          key: REMOTE_LOKI_HOST
